<template>
  <a
    class="text-xs" alt="site"
    href="https://girid.yunyoujun.cn" target="_blank"
    op="60"
    my="1"
  >
    <span>Generated by
      <span class="border-b">
        girid.yunyoujun.cn
      </span>
    </span>
  </a>
</template>
