/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimationListGrid: typeof import('./components/AnimationListGrid.vue')['default']
    CharacterCard: typeof import('./components/CharacterCard.vue')['default']
    CharacterCardImage: typeof import('./components/CharacterCardImage.vue')['default']
    CharacterGrid: typeof import('./components/CharacterGrid.vue')['default']
    CharacterListGrid: typeof import('./components/CharacterListGrid.vue')['default']
    CharacterName: typeof import('./components/CharacterName.vue')['default']
    CharacterSearch: typeof import('./components/CharacterSearch.vue')['default']
    ChooseCharacterModal: typeof import('./components/ChooseCharacterModal.vue')['default']
    CopyGirid: typeof import('./components/CopyGirid.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DownloadGirid: typeof import('./components/DownloadGirid.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FriendCard: typeof import('./components/FriendCard.vue')['default']
    FriendGrid: typeof import('./components/FriendGrid.vue')['default']
    FriendName: typeof import('./components/FriendName.vue')['default']
    GiridCardImage: typeof import('./components/GiridCardImage.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    NicknameInput: typeof import('./components/NicknameInput.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBottomMenu: typeof import('./components/TheBottomMenu.vue')['default']
    UploadImageBtn: typeof import('./components/UploadImageBtn.vue')['default']
    YlfBottomMenu: typeof import('./../node_modules/.pnpm/@yunlefun+vue-components@0.0.5-beta.4/node_modules/@yunlefun/vue-components/dist/runtime/components/YlfBottomMenu.vue')['default']
    YlfBottomMenuItem: typeof import('./../node_modules/.pnpm/@yunlefun+vue-components@0.0.5-beta.4/node_modules/@yunlefun/vue-components/dist/runtime/components/YlfBottomMenuItem.vue')['default']
  }
}
